main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('story5/', views.story5, name='story5'),
    path('story5/detailmatkul/<int:id>/', views.detail, name='detailmatkul'),
    path('story5/deletematkul/<int:id>/', views.delete, name='deletematkul'),
    path('story7/', views.story7, name='story7'),
    path('story8/', views.story8, name='story8'),
    path('user/', views.story9,name='story9'),
    path('user/login/', views.login_user,name='login'),
    path('user/logout/', views.logout_user,name='logout'),
    path('user/signup/', views.signup_user,name='signup')

]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    ]

main/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class modelMatkul(models.Model):
    mataKuliah = models.CharField(max_length = 100)
    dosenPengajar = models.CharField(max_length = 100)
    jumlahSKS = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(6)])
    deskripsi = models.TextField(blank=True , null=True)
    semester = models.CharField(max_length = 30)
    ruangan = models.CharField(max_length = 100)

main/forms.py
from django import forms
from .models import modelMatkul

class formMatkul(forms.ModelForm):
	class Meta:
		model = modelMatkul
		fields = '__all__'

main/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .forms import formMatkul
from .models import modelMatkul
from django.http import HttpResponseRedirect
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def home(request):
    return render(request, 'main/home.html')

def story5(request):
    formKukuh = formMatkul()

    if request.method=='POST':
        formKukuh = formMatkul(request.POST)
        if formKukuh.is_valid():
            formKukuh.save()
            return redirect('/story5')

    previewTable = modelMatkul.objects.all()
    dataKukuh = {"createMatkul" : formKukuh, "tampilkanTable" : previewTable}
    return render(request, 'main/Story5.html', dataKukuh)

def detail(request, id):
    matkul = get_object_or_404(modelMatkul, id=id)
    detailMatkul = {"createDetail" : matkul}
    return render(request, 'main/Details.html', detailMatkul)

def delete(request, id):
    delete = modelMatkul.objects.filter(id=id)
    delete.delete()
    return HttpResponseRedirect('/story5')

def story7(request):
    return render(request, 'main/story7.html')

def story8(request):
    return render(request, 'main/story8.html')

def story9(request):
    return render(request,'main/user.html')

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print("{}: {} ".format(username,password))
        if not username or not password:
            messages.error(request, "Please enter username / password correctly")
            return HttpResponseRedirect('/user/login')

        user = authenticate(request,username = username,password = password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect('/user/')
        else:
            messages.error(request, "Wrong credentials (Wrong Username / Password)")
            return HttpResponseRedirect('/user/login')
    else:
        return render(request,'main/login.html')

def logout_user(request):
    logout(request)
    messages.success(request, "Successfully logged out.")
    return HttpResponseRedirect('/user/')

def signup_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if not username or not password:
            messages.error(request, "Please enter username / password correctly")
            return HttpResponseRedirect('/user/signup')
        if User.objects.filter(username__iexact = username).exists():
            messages.error(request, "Username taken")
            return HttpResponseRedirect('/user/signup')
        else:
            user = User.objects.create_user(username=username, password=password)
            user.save()
            return HttpResponseRedirect('/user/login')
    else:
        return render(request,'main/signup.html')

main/templates/main/Details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
	<title>Profilnya Kukuh Nih!</title>
{% endblock meta %}

{% block content %}
	<br>	
	<table class="my-table">
        <tr>
            <td><p>Nama Mata Kuliah</p></td>
            <td><p class="pl-4">: {{createDetail.mataKuliah}}</p></td>
        </tr>
        <tr>
            <td><p>Nama Dosen</p></td>
            <td><p class="pl-4">: {{createDetail.dosenPengajar}}</p></td>
        </tr>
        <tr>
            <td><p>Jumlah SKS</p></td>
            <td><p class="pl-4">: {{createDetail.jumlahSKS}}</p></td>
        </tr>
        <tr>
            <td><p>Semester</p></td>
            <td><p class="pl-4">: {{createDetail.semester}}</p></td>
        </tr>
        <tr>
            <td><p>Ruangan</p></td>
            <td><p class="pl-4">: {{createDetail.ruangan}}</p></td>
        </tr>
        <tr>
            <td><p>Deskripsi</p></td>
            <td><p class="pl-4">: {{createDetail.deskripsi}}</p></td>
        </tr>
    </table>

	<br>
	<footer>
		<a href="https://www.instagram.com" target="_blank">
		<img src="{% static 'img/InstagramVector.png'%}" alt="Instagram Icon" width="50" height="50" style="padding: 5px 10px;" align="right">
		</a>
		<a href="https://www.twitter.com" target="_blank">
		<img src="{% static 'img/TwitterVector.png'%}" alt="Instagram Icon" width="50" height="50" style="padding: 5px 10px; border-radius: 100%;" class="round-border" align="right">
		</a>
		<a href="https://www.youtube.com" target="_blank">
		<img src="{% static 'img/Youtube.png'%}" alt="Youtube Icon" width= auto; height="60" style="padding: 0px 10px;" class="round-border" align="right">
		</a>
	</footer>
{% endblock content %}

main/templates/main/Story5.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
	<title>Profilnya Kukuh Nih!</title>
{% endblock meta %}

{% block content %}
	<br>
	<div>Jadwal matkul</div>
	<form method="POST">
	{% csrf_token %}
	<table>
		{{createMatkul.as_p}}
	</table>
	<button type="Submit" name="submit">Submit</button>
	</form>
	<br>
	<table>
		<thead>
			<tr>
			  <th scope="col">No.</th>
			  <th scope="col">Nama Matkul</th>
			  <th scope="col">Pilihan</th>			  
			</tr>
			</thead>
		{% for mat in tampilkanTable %}
		<tr>
		  <th scope="row">{{ forloop.counter }}</th>
		  <th scope="row">{{mat.mataKuliah}}</th>
		  <th>
			<a class="btn btn-dark" href="detailmatkul/{{mat.id}}/">Details</a>
			<a class="btn btn-warning" href="deletematkul/{{mat.id}}/">Delete</a>
		  </th>
		</tr>
		{% endfor %}
	</table>
	<br>
	<footer>
		<a href="https://www.instagram.com" target="_blank">
		<img src="{% static 'img/InstagramVector.png'%}" alt="Instagram Icon" width="50" height="50" style="padding: 5px 10px;" align="right">
		</a>
		<a href="https://www.twitter.com" target="_blank">
		<img src="{% static 'img/TwitterVector.png'%}" alt="Instagram Icon" width="50" height="50" style="padding: 5px 10px; border-radius: 100%;" class="round-border" align="right">
		</a>
		<a href="https://www.youtube.com" target="_blank">
		<img src="{% static 'img/Youtube.png'%}" alt="Youtube Icon" width= auto; height="60" style="padding: 0px 10px;" class="round-border" align="right">
		</a>
	</footer>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
	<title>Profilnya Kukuh Nih!</title>
{% endblock meta %}

{% block content %}
  <br>
	<div class="center montserrat" style="padding-top: 200px; padding-bottom: 200px">
	    <p>Hey, You Found Me!</p>
	</div>
	<div class="main" id="About" style="padding-top: 150px">
		<img src="{% static 'img/PPKukuh.jpg'%}" alt="Profile Pic Kukuh" class="center round-border" width="300" height="300" border="3" style="border-radius: 100%  ">
	</div>
	<br>
	<div style="padding-top: 300px">
		<table>
		  <tr>
		    <td>Nama</td>
		    <td>Kukuh Satrio Wicaksono</td>
		  </tr>
		  <tr>
		    <td>NPM</td>
		    <td>1906399045</td>
		  </tr>
		  <tr>
		    <td>Angkatan</td>
		    <td>MAUNG (2019)</td>
		  </tr>
		  <tr>
		    <td>Tempat Kuliah</td>
		    <td>Fakultas Ilmu Komputer UI</td>
		  </tr>
		  <tr>
		    <td>Hobi</td>
		    <td>Berbaring</td>
		  </tr>
		  <tr>
		    <td>Tentang Saya</td>
		    <td>Bla bla bla bla...asdklasnmdkassndkjass dkajsdnkasj dkasjd kajsd kassjd kasdjas dkasjdn kajs,dnkas dj,malsdj aldiwn akeljnaef</td>
		  </tr>  
		</table>
	</div>
	<!-- Riwayat Pendidikan -->
  	<div style="padding-bottom: 200px">
	  	<h1 align="center" style="padding-top: 300px">Riwayat Pendidikan</h1>
	  	<table>    
	  	  <tr>
		    <td>SD</td>
		    <td>SDIF Al-Fikri Depok</td>
		  </tr>
		  <tr>
		    <td>SMP</td>
		    <td>SMPN 3 Depok</td>
		  </tr>
		  <tr>
		    <td>SMA</td>
		    <td>SMAN 13 Depok</td>
		  </tr>
		  <tr>
		    <td>Pendidikan Tinggi</td>
		    <td>Universitas Indonesia</td>	
		  </tr>   
		</table>
	  		
  	</div>
	<br>
	<footer>
		<a href="https://www.instagram.com" target="_blank">
		<img src="{% static 'img/InstagramVector.png'%}" alt="Instagram Icon" width="50" height="50" style="padding: 5px 10px;" align="right">
		</a>
		<a href="https://www.twitter.com" target="_blank">
		<img src="{% static 'img/TwitterVector.png'%}" alt="Instagram Icon" width="50" height="50" style="padding: 5px 10px; border-radius: 100%;" class="round-border" align="right">
		</a>
		<a href="https://www.youtube.com" target="_blank">
		<img src="{% static 'img/Youtube.png'%}" alt="Youtube Icon" width= auto; height="60" style="padding: 0px 10px;" class="round-border" align="right">
		</a>
	</footer>
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}

{% block title %}Login Page{% endblock %}

{% block content %}
    <div class="container">
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <script>
                alert("{{ message }}")
            </script>
            {% endfor %}
        </ul>
        {% endif %}
  
        {% if user.is_authenticated %}
            <h1>Selamat Datang {{ user.username }} !</h1>
                <a class="btn btn-primary" href="{% url 'main:logout' %}" style="color: #fff800; background-color: black; border-color: black;">Logout</a>
        {% else %}
        <h1>Log In</h1>
        <p>Don't have an acoount? You can create it  <a href="{% url 'main:signup' %}">here</a></p>
        <form  action="{% url 'main:login' %}" method="POST">
            {% csrf_token %}
                <label for="#username">Username</label>
                <input id="username" name="username" class="form-control" type="text">
                <label for="#password">Password</label>
                <input id="password" name="password" class="form-control" type="password">
                <br>
                <input id="sub-login" class="btn btn-primary" type="submit" style="color: #fff800; background-color: black; border-color: black;" value="Log In">
            </form>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/signup.html
{% extends 'base.html' %}

{% block title %}Signup Page{% endblock %}

{% block content %}
    <div class="container">
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <script>
                alert("{{ message }}")
            </script>
            {% endfor %}
        </ul>
        {% endif %}
  
        {% if user.is_authenticated %}
            <h1>Logged as {{ user.username }}</h1>
                <a class="btn btn-primary" href="{% url 'main:logout' %}" style="color: #fff800; background-color: black; border-color: black;">Logout</a>
                {% else %}
                    <h1>Sign Up</h1>
                    <p>Have an account? You can log in <a href="{% url 'main:login' %}" >here</a></p>
                    <form  action="{% url 'main:signup' %}" method="POST">
                        {% csrf_token %}
                        <label for="#username">Username</label>
                        <input id="username" name="username" class="form-control" type="text">
                        <label for="#password">Password</label>
                        <input id="password" name="password" class="form-control" type="password">
                        <br>
                        <input id="sub-signup" class="btn btn-primary" style="color: #fff800; background-color: black; border-color: black;" type="submit" value="Sign me up!">
                    </form>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/story7.html
{% extends "base.html" %}
{% block meta %}
<title>Accordion</title>
{% endblock meta %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/accordion.css' %}">
<div class="wrapper col-12">
    <div class="d-flex flex-column justify-content-start align-items-center py-5 col-lg-8 mx-auto">
        <h1 class="mb-5">Holla, here's some information about me!</h1>
        <div class="accordion col-md-10 p-0 mt-2 accordion-1" id="accor1">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Introduction</h2>
                <div class="buttons d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>Hello, you can call me Kukuh, i'm 19 years old</p>
                    <p>I love doing design (even tho this app looks so empty, haha) And i have a passion in copywriting.</p>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-2" id="accor2">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Current Activities</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>Disclaimer, i'm not that productive during this pandemic, so.. it's basically just games, youtube, and manga other than online classes. Ah, sometimes i do cook too.</p>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-3" id="accor3">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Experiences</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>As i said earlier, i'm not that productive during this pandemic, but here you go..</p>
                    <ul class="m-0">
                        <li>Deputy Chief Bureau of FUKI Corp. at Forum Ukhuwah dan Kajian Islam Fasilkom UI</li>
                        <li>Program Director & Head of Design for Startup Weekend UI</li>
                        <li>Staff of Sponsorship for PERAK Fasilkom</li>
                        <li>PComing Soon!</li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-4" id="accor4">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Achievements</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>This is the tricky one, what is my achievments? hmm, let me think..</p>
                    <p>.</p>
                    <p>.</p>
                    <p>.</p>
                    <p>.</p>
                    <p>.</p>
                    <p>Look A Plane!</p>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-5" id="accor5">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Contact</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0 d-flex flex-column">
                    <div class="d-flex mt-2">
                        <img src="https://www.stickpng.com/assets/images/58e91afdeb97430e81906504.png" height="30"
                            width="30" class="mr-2">
                        <h4><a href="https://www.linkedin.com/in/KukuhSatrioW/" target="_blank">LinkedIn</a></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/accordion.js' %}"></script>
{% endblock %}

main/templates/main/story8.html
{% extends "base.html" %}
{% load static %}


{% block meta %}
<title>Books</title>
{% endblock meta %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/booksfinder.css' %}">

<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="form-group col">
                <h2>Books Finder</h2>
                <input id="search" class="form-control" placeholder="Insert book title...">
            </div>
            <div class="form-group col-auto">
                <button id="button" type="button" class="btn btn-dark">Search</button>

                <div class="mytable">
                    <div style="overflow-x:auto;">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col-2">No.</th>
                                    <th scope="col-2">Cover</th>
                                    <th scope="col-2">Title</th>
                                    <th scope="col-2">Author</th>
                                    <th scope="col-2" style="width: 1200px;">Description</th>
                                </tr>
                            </thead>
                            <tbody class="result">
                                <!-- Ajax Content -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/booksfinder.js' %}"></script>
{% endblock %}

main/templates/main/user.html
{% extends 'base.html' %}

{% block title %}Story9{% endblock %}

{% block content %}
<div style="margin-top: 1em;" class="container">

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
        <h3>Selamat Datang {{ user.username }} !</h3>
        <br>
        <br>    

        <a id='sub-logout' class="btn btn-primary" href="{% url 'main:logout' %}" style="color: #fff800; background-color: black; border-color: black;">Logout</a>
      {% else %}
        <h1>You are not logged in.</h1>
        <br>
        <h3>Do you have an account?</h3>
        <a id='login' class="btn btn-success" href="{% url 'main:login' %}" style="color: #fff800; background-color: black; border-color: black;">Log in</a>
        <a id='signup' class="btn btn-outline-success" href="{% url 'main:signup' %}" style="color: black; border-color: black;">Sign up</a>
      {% endif %}

</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

  {% block meta %}
  {% endblock meta %}
</head>

<body>
	<navbar>
		<div class="navbar" id="myNavbar">
		  <a href="/">
		  <img src="{% static 'img/K$W Black.png'%}" style="float: left; max-height: 50px">
		  </a>
		  <a style="float: right;">Contact</a>
		  <a style="float: right;">Experience</a>
		  <a style="float: right;" href="#About">About</a>
		  <a style="float: right;" href="/story5">Story 5</a>
		  <a style="float: right;" href="/story7">Story 7</a>
		  <a style="float: right;" href="/story8">Story 8</a>
		  <a style="float: right;" href="/user">Story 9</a>
		</div>
	</navbar>
	
	<script type="text/javascript" src="script.js"></script>

  {% block content %}
  {% endblock content %}
</body>

</html>